[package]
name = "risc0-ecdsa"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
clap = "4.4"
risc0-ecdsa-methods = { path = "./methods" }
k256 = { version = "0.13", features = ["serde"] }
rand_core = "0.6.4"
risc0-zkvm = { version = "0.21.0" }
env_logger = "0.10"
serde = "1.0"
